mysite/human/urls.py
from .views import HumanView, DetailView
from django.urls import path

app_name = 'human'

urlpatterns = [
    path('', HumanView.as_view(), name='humans'),
    path('<int:pk>', DetailView.as_view(), name='person'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

import django


urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/profile/', include('human.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

mysite/polls/urls.py
from django.urls import path
from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('test/', views.TestView.as_view(), name='test')
]

mysite/human/models.py
# from django.contrib.auth.models import 
from django.db import models


class Human(models.Model):
    name = models.CharField(max_length=32)
    age = models.IntegerField()
    # children = models.ManyToManyField('self', default=None)
    relatives = models.ManyToManyField('self', related_name='relatives', default=None)
    # children = models.ForeignKey('self', related_name='parent', on_delete=models.CASCADE, default=None, null=True)


    def __str__(self):
        return self.name

mysite/polls/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def __repr__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class OtherQueestion(models.Model):
    CHOICE1 = 'CH1'
    CHOICE2 = 'CH2'
    OTHER_Q_CHOICES = (
        (CHOICE1, 'CH1'),
        (CHOICE2, 'CH2'),
    )

    q_text = models.CharField(
        max_length=200,
        choices=OTHER_Q_CHOICES,
        default=CHOICE1,
    )
# Create your models here.

mysite/human/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Human


class HumanView(generic.ListView):
    template_name = 'human/humans.html'
    context_object_name = 'humans_list'

    def get_queryset(self):
        return Human.objects.all()


class DetailView(generic.DetailView):
    template_name = 'human/person.html'
    model = Human

# Create your views here.

mysite/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Question, Choice, OtherQueestion

class TestView(generic.ListView): 
    template_name = 'polls/test.html'
    context_object_name = 'test_q'


class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]
    

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/result.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()   
        if request.user.is_staff:
            return HttpResponseRedirect(reverse('polls:results', args=
            (question.id,)))
        else:
            return HttpResponseRedirect('/login/')
        

mysite/human/templates/human/base.html
<title>Humans list</title>
{% comment %} {% endblock  %} {% endcomment %}
<h1>Human database</h1>
<hr>

mysite/human/templates/human/humans.html
{% comment %} {% extends 'base.html' %} {% endcomment %}

{% comment %} {% block head %} {% endcomment %}
{% include 'human/base.html' %}

{% comment %} {% block body %} {% endcomment %}
{% if humans_list %}
<ul>
    {% for human in humans_list %}
        <li><a href="{% url 'human:person' human.id %}">{{ human.name }}</a></li>
        {{ human.age }} {{' years old'}}
        <hr>
    {% endfor %}
</ul>
{% else %} 
    <p>There are no humans</p>
{% endif %}
{% comment %} {% endblock  %} {% endcomment %}
<a href="{% url 'logout'%}">logout</a>

mysite/human/templates/human/person.html
{% include 'human/base.html' %}

<h1>{{ human.name }}</h1>

</br>{{ 'relatives: '}}

<ul>
    {% for h in human.relatives.all %}
        <li><a href="{% url 'human:person' h.id %}">{{ h.name }}</a></li>
        {% for r in h.relatives.all %}
            <li><a href="{% url 'human:person' r.id %}">{{ r.name }}</a></li>
            
        {% endfor %}
    {% endfor %}
</ul>
<a href="{% url 'human:humans' %}">Back to list of humans?</a>

</br><a href="{% url 'logout'%}">logout</a>

mysite/polls/templates/polls/detail.html
<!--{{ question }} - might look this way, it's easier-->
<!--<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul> -->
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        {% comment %} <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li> {% endcomment %}
        <!-- That's how links looks like -->
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<a href="/login/">Log out</a>

mysite/polls/templates/polls/result.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

mysite/polls/templates/polls/test.html
{% if test_q %}
    <ul>
    {% for q in test_q %}
        <li><a href="{% url 'polls:test' %}">{{ q.q_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Nothing to show</p>
{% endif %}